// generate_sql.js
const memberDataList = [
  {
    email: 'jane.smith@example.com',
    name: 'Jane Smith',
    initials: 'JS',
    title: 'Social Entrepreneur at Impact Ventures',
    bio: 'Passionate about creating positive social impact through innovative solutions and community engagement.',
    location: 'Mumbai, India',
    skills: ['Social Innovation', 'Impact Measurement', 'Community Building'],
    expertise: ['Sustainability', 'Social Enterprise'],
    experience: ['Founder at Social Ventures (5 years)', 'Impact Consultant at NGO Partners (3 years)'],
    education: ['Masters in Social Entrepreneurship - LSE', 'Bachelor in Economics - Delhi University'],
    lookingFor: ['Partnerships', 'Funding Opportunities', 'Mentorship'],
    offering: ['Strategic Guidance', 'Network Access', 'Impact Expertise'],
    website: 'https://janesmith.social',
    twitter: '@janesmith',
    linkedin: 'linkedin.com/in/janesmith',
    cohort: '2022',
  },
  {
    email: 'rahul.kumar@example.com',
    name: 'Rahul Kumar',
    initials: 'RK',
    title: 'Tech Entrepreneur • Scaling Startups',
    bio: 'Building tech startups with social impact at the core. Passionate about using technology for good.',
    location: 'Mumbai, India',
    skills: ['Technology', 'Entrepreneurship', 'Mentoring', 'Product Development'],
    expertise: ['SaaS', 'Mobile Apps', 'AI/ML'],
    experience: ['Founder & CEO at TechForGood (6 years)', 'CTO at Digital Solutions Inc (4 years)'],
    education: ['Bachelor in Computer Science - IIT Mumbai', 'Nanodegree in AI - Udacity'],
    lookingFor: ['Technical Co-founders', 'Investors', 'Tech Partnerships'],
    offering: ['Technical Mentorship', 'Product Guidance', 'Network in Tech'],
    website: 'https://rahulkumar.tech',
    github: 'github.com/rahulkumar',
    linkedin: 'linkedin.com/in/rahulkumar',
    cohort: '2021',
  },
  {
    email: 'anjali.patel@example.com',
    name: 'Anjali Patel',
    initials: 'AP',
    title: 'Social Impact Consultant',
    bio: 'Focused on rural development and education initiatives. 10+ years of experience in development sector.',
    location: 'Delhi, India',
    skills: ['Education', 'Rural Development', 'Impact Assessment'],
    expertise: ['Program Design', 'Monitoring & Evaluation', 'Community Engagement'],
    experience: ['Development Consultant at World Bank (7 years)', 'Program Manager at UNICEF (5 years)'],
    education: ['Masters in Public Administration - Delhi School of Economics', 'Bachelor in Social Work - Delhi University'],
    lookingFor: ['Project Collaborations', 'Research Partners', 'Field Implementation'],
    offering: ['Program Design Expertise', 'Impact Measurement Framework', 'Policy Guidance'],
    linkedin: 'linkedin.com/in/anjalipatel',
    cohort: '2020',
  },
  {
    email: 'sanjay.mehta@example.com',
    name: 'Sanjay Mehta',
    initials: 'SM',
    title: 'Sustainable Agriculture Expert',
    bio: 'Promoting sustainable farming practices and organic agriculture. Connected with 5000+ farmers.',
    location: 'Pune, India',
    skills: ['Agriculture', 'Sustainability', 'Environment', 'Farmer Training'],
    expertise: ['Organic Farming', 'Agricultural Technology', 'Supply Chain'],
    experience: ['Founder at GreenFields Initiative (8 years)', 'Agriculture Scientist at ICAR (6 years)'],
    education: ['Masters in Agricultural Sciences - University of Pune', 'PhD in Sustainable Agriculture (ongoing)'],
    lookingFor: ['Technology Partners', 'Market Access', 'Research Collaboration'],
    offering: ['Agricultural Expertise', 'Farmer Network Access', 'Training Programs'],
    website: 'https://greenfields.farm',
    linkedin: 'linkedin.com/in/sanjaymehta',
    cohort: '2019',
  },
  {
    email: 'meera.gupta@example.com',
    name: 'Meera Gupta',
    initials: 'MG',
    title: 'Healthcare Innovation Lead',
    bio: 'Building healthcare solutions for underserved rural areas. Digital health enthusiast.',
    location: 'Bangalore, India',
    skills: ['Healthcare', 'Innovation', 'Technology', 'Digital Health'],
    expertise: ['Telemedicine', 'Health Tech', 'Public Health'],
    experience: ['Co-founder at HealthConnect (4 years)', 'Healthcare Consultant at McKinsey (5 years)'],
    education: ['Masters in Health Administration - AIIMS Delhi', 'Bachelor in Medicine - Bangalore Medical College'],
    lookingFor: ['Healthcare Partnerships', 'Government Collaborations', 'Tech Integration'],
    offering: ['Medical Expertise', 'Healthcare Networks', 'Regulatory Guidance'],
    linkedin: 'linkedin.com/in/meeragupta',
    cohort: '2022',
  },
  {
    email: 'priya.sharma@example.com',
    name: 'Priya Sharma',
    initials: 'PS',
    title: 'Education Technology Pioneer',
    bio: 'Building EdTech solutions to democratize quality education. Passionate about inclusive learning.',
    location: 'Hyderabad, India',
    skills: ['EdTech', 'Curriculum Design', 'Online Learning'],
    expertise: ['E-Learning Platforms', 'Pedagogy', 'Student Engagement'],
    experience: ['Founder at LearnHub (5 years)', 'Education Manager at TCS (4 years)'],
    education: ['Masters in Education Technology - University of Hyderabad', 'Bachelor in Education - Central University'],
    lookingFor: ['Technology Partners', 'School Networks', 'Funding'],
    offering: ['EdTech Expertise', 'Curriculum Content', 'Training'],
    twitter: '@priyasharma_ed',
    linkedin: 'linkedin.com/in/priyasharma',
    cohort: '2021',
  },
  {
    email: 'vikram.singh@example.com',
    name: 'Vikram Singh',
    initials: 'VS',
    title: 'Environmental Conservation Leader',
    bio: 'Working on forest conservation and biodiversity projects across Eastern India.',
    location: 'Kolkata, India',
    skills: ['Environmental Conservation', 'Biodiversity', 'Wildlife'],
    expertise: ['Forest Management', 'Community Conservation', 'Climate Action'],
    experience: ['Director at Forest Protection Initiative (7 years)', 'Biologist at Wildlife Institute (5 years)'],
    education: ['PhD in Forest Ecology - University of Kolkata', 'Masters in Biology - Delhi University'],
    lookingFor: ['Conservation Partnerships', 'Research Funding', 'International Collaborations'],
    offering: ['Conservation Expertise', 'Research Data', 'Field Implementation'],
    linkedin: 'linkedin.com/in/vikramsingh',
    cohort: '2020',
  },
  {
    email: 'neha.kapoor@example.com',
    name: 'Neha Kapoor',
    initials: 'NK',
    title: 'Women Empowerment Advocate',
    bio: 'Dedicated to women empowerment through skill development and financial inclusion.',
    location: 'Chandigarh, India',
    skills: ['Women Empowerment', 'Financial Inclusion', 'Skill Development'],
    expertise: ['Microfinance', 'Vocational Training', 'Gender Studies'],
    experience: ['Executive Director at Women First (6 years)', 'Program Officer at SEWA (4 years)'],
    education: ['Masters in Gender Studies - Delhi University', 'Bachelor in Commerce - Chandigarh University'],
    lookingFor: ['Funding Partners', 'Skill Training Content', 'Market Linkages'],
    offering: ['Women Networks', 'Training Programs', 'Policy Advocacy'],
    twitter: '@nehakapoor_women',
    linkedin: 'linkedin.com/in/nehakapoor',
    cohort: '2021',
  },
  {
    email: 'arjun.prabhu@example.com',
    name: 'Arjun Prabhu',
    initials: 'AP',
    title: 'Fintech Innovator',
    bio: 'Creating financial technology solutions for underbanked communities. Payment systems expert.',
    location: 'Bangalore, India',
    skills: ['Fintech', 'Blockchain', 'Payment Systems', 'Software Engineering'],
    expertise: ['Digital Payments', 'Cryptocurrency', 'Financial Inclusion'],
    experience: ['CTO at PayTech Solutions (5 years)', 'Software Engineer at Goldman Sachs (6 years)'],
    education: ['Masters in Computer Science - University of Bangalore', 'Bachelor in IT - VIT University'],
    lookingFor: ['Technical Partnerships', 'Enterprise Clients', 'Regulatory Support'],
    offering: ['Technical Expertise', 'Open Source Solutions', 'Dev Team'],
    github: 'github.com/arjunprabhu',
    linkedin: 'linkedin.com/in/arjunprabhu',
    cohort: '2022',
  },
  {
    email: 'deepa.nair@example.com',
    name: 'Deepa Nair',
    initials: 'DN',
    title: 'Sustainable Fashion Entrepreneur',
    bio: 'Building sustainable fashion brands with ethical supply chains. Promoting responsible consumption.',
    location: 'Kochi, India',
    skills: ['Fashion', 'Sustainability', 'Supply Chain', 'Social Enterprise'],
    expertise: ['Ethical Fashion', 'Sustainable Materials', 'Artisan Collaboration'],
    experience: ['Founder at EcoStyle Creations (4 years)', 'Fashion Designer at International Brands (5 years)'],
    education: ['Masters in Fashion Design - NIFT Delhi', 'Bachelor in Textiles - University of Kochi'],
    lookingFor: ['Supplier Networks', 'Market Access', 'Impact Investors'],
    offering: ['Fashion Expertise', 'Supply Chain Support', 'Artisan Networks'],
    website: 'https://ecostylecreations.com',
    linkedin: 'linkedin.com/in/deepanair',
    cohort: '2021',
  },
  {
    email: 'rohan.kapoor@example.com',
    name: 'Rohan Kapoor',
    initials: 'RK',
    title: 'Urban Development Strategist',
    bio: 'Focused on sustainable urban development and smart city solutions. Working across 20+ cities.',
    location: 'Gurgaon, India',
    skills: ['Urban Development', 'Smart Cities', 'Infrastructure', 'Planning'],
    expertise: ['City Planning', 'Transportation', 'Sustainability in Cities'],
    experience: ['Urban Consultant at McKinsey (6 years)', 'City Planner at Ministry of Urban Affairs (5 years)'],
    education: ['Masters in Urban Planning - School of Planning & Architecture', 'Bachelor in Architecture - Delhi University'],
    lookingFor: ['Government Partnerships', 'Infrastructure Projects', 'Tech Integration'],
    offering: ['Urban Planning Expertise', 'Government Connections', 'Feasibility Studies'],
    linkedin: 'linkedin.com/in/rohankapoor',
    cohort: '2020',
  },
  {
    email: 'divya.sharma@example.com',
    name: 'Divya Sharma',
    initials: 'DS',
    title: 'Healthcare Policy Advocate',
    bio: 'Advocating for inclusive healthcare policies and access to medicines for all.',
    location: 'New Delhi, India',
    skills: ['Healthcare Policy', 'Advocacy', 'Public Health'],
    expertise: ['Policy Drafting', 'Healthcare Economics', 'Government Relations'],
    experience: ['Policy Advisor at Ministry of Health (5 years)', 'Researcher at Health Analytics (4 years)'],
    education: ['Masters in Public Health - Delhi School of Economics', 'Bachelor in Medicine - Delhi Medical College'],
    lookingFor: ['Policy Research Collaborations', 'International Partnerships'],
    offering: ['Policy Expertise', 'Research Data', 'Government Connections'],
    linkedin: 'linkedin.com/in/divyasharma',
    cohort: '2020',
  },
  {
    email: 'sameer.khan@example.com',
    name: 'Sameer Khan',
    initials: 'SK',
    title: 'Water & Sanitation Specialist',
    bio: 'Implementing WASH solutions in remote villages. Installed water systems for 50+ communities.',
    location: 'Nagpur, India',
    skills: ['Water Management', 'Sanitation', 'Community Development'],
    expertise: ['WASH Solutions', 'Infrastructure', 'Community Engagement'],
    experience: ['Program Director at WaterCare (7 years)', 'Field Engineer at UNICEF (5 years)'],
    education: ['Masters in Environmental Engineering - IIT Bombay', 'Bachelor in Civil Engineering - NIT Nagpur'],
    lookingFor: ['Funding for Projects', 'Technical Partnerships', 'Government Support'],
    offering: ['Technical Expertise', 'Community Networks', 'Implementation Support'],
    linkedin: 'linkedin.com/in/sameerkhan',
    cohort: '2019',
  },
  {
    email: 'ritika.singh@example.com',
    name: 'Ritika Singh',
    initials: 'RS',
    title: 'Mental Health Advocate',
    bio: 'Promoting mental health awareness and accessible counseling services in India.',
    location: 'Pune, India',
    skills: ['Mental Health', 'Counseling', 'Awareness Programs'],
    expertise: ['Clinical Psychology', 'Community Mental Health', 'Crisis Support'],
    experience: ['Founder at MindCare Foundation (4 years)', 'Therapist at Apollo Hospitals (6 years)'],
    education: ['Masters in Clinical Psychology - Pune University', 'Bachelor in Psychology - Delhi University'],
    lookingFor: ['Partnerships with Healthcare Providers', 'Funding'],
    offering: ['Mental Health Expertise', 'Counselor Network', 'Training Programs'],
    linkedin: 'linkedin.com/in/ritikasingh',
    cohort: '2022',
  },
  {
    email: 'nikhil.verma@example.com',
    name: 'Nikhil Verma',
    initials: 'NV',
    title: 'Clean Energy Entrepreneur',
    bio: 'Building solar energy solutions for rural electrification. Impacting 10,000+ households.',
    location: 'Rajasthan, India',
    skills: ['Renewable Energy', 'Solar Technology', 'Entrepreneurship'],
    expertise: ['Solar Engineering', 'Energy Management', 'Off-Grid Solutions'],
    experience: ['Founder at SunEnergy India (6 years)', 'Engineer at RenewTech (4 years)'],
    education: ['Masters in Energy Engineering - IIT Delhi', 'Bachelor in Electrical Engineering - NIT Jaipur'],
    lookingFor: ['Funding', 'Supply Chain Partners', 'Government Contracts'],
    offering: ['Energy Expertise', 'Technical Support', 'Supplier Networks'],
    linkedin: 'linkedin.com/in/nikhilverma',
    cohort: '2020',
  },
  {
    email: 'pooja.malhotra@example.com',
    name: 'Pooja Malhotra',
    initials: 'PM',
    title: 'Disability Inclusion Specialist',
    bio: 'Working on inclusive employment and accessibility for persons with disabilities.',
    location: 'Mumbai, India',
    skills: ['Disability Inclusion', 'Accessibility', 'Employment'],
    expertise: ['Inclusive Design', 'Vocational Rehabilitation', 'Rights Advocacy'],
    experience: ['Director at Include India (5 years)', 'Accessibility Consultant at Tech Companies (6 years)'],
    education: ['Masters in Social Work - Mumbai University', 'Bachelor in Commerce - Mumbai University'],
    lookingFor: ['Corporate Partnerships', 'Technology Integration'],
    offering: ['Disability Expertise', 'Community Networks', 'Accessible Design Guidance'],
    linkedin: 'linkedin.com/in/poojamalhotra',
    cohort: '2021',
  },
  {
    email: 'aditya.seth@example.com',
    name: 'Aditya Seth',
    initials: 'AS',
    title: 'AI/ML Research Lead',
    bio: 'Using AI and machine learning to solve social problems. Research focused on bias reduction.',
    location: 'Bangalore, India',
    skills: ['AI', 'Machine Learning', 'Data Science', 'Research'],
    expertise: ['Deep Learning', 'NLP', 'Computer Vision', 'Ethical AI'],
    experience: ['AI Researcher at Google India (5 years)', 'Data Scientist at IBM (4 years)'],
    education: ['PhD in Machine Learning - IIT Delhi', 'Masters in Computer Science - University of Pune'],
    lookingFor: ['Research Collaborations', 'Datasets', 'Academic Partnerships'],
    offering: ['AI Expertise', 'Research Guidance', 'Technical Solutions'],
    github: 'github.com/adityaseth',
    linkedin: 'linkedin.com/in/adityaseth',
    cohort: '2022',
  },
  {
    email: 'sneha.joshi@example.com',
    name: 'Sneha Joshi',
    initials: 'SJ',
    title: 'Arts & Culture Preservationist',
    bio: 'Documenting and preserving traditional Indian arts and crafts. Working with 200+ artisans.',
    location: 'Jaipur, India',
    skills: ['Cultural Heritage', 'Arts Preservation', 'Artisan Support'],
    expertise: ['Traditional Crafts', 'Cultural Documentation', 'Market Development'],
    experience: ['Founder at Heritage Arts Foundation (6 years)', 'Curator at National Museum (4 years)'],
    education: ['Masters in Art History - Delhi University', 'Bachelor in Fine Arts - Jaipur University'],
    lookingFor: ['Tourism Partnerships', 'International Markets', 'Documentation Funding'],
    offering: ['Artisan Networks', 'Cultural Expertise', 'Market Linkages'],
    website: 'https://heritagearts.org',
    linkedin: 'linkedin.com/in/snehajoshi',
    cohort: '2021',
  },
  {
    email: 'vikash.patel@example.com',
    name: 'Vikash Patel',
    initials: 'VP',
    title: 'Community Sports Developer',
    bio: 'Promoting sports and fitness in underprivileged communities. Coaching 500+ youth.',
    location: 'Ahmedabad, India',
    skills: ['Sports Development', 'Community Engagement', 'Youth Training'],
    expertise: ['Athletic Coaching', 'Sports Management', 'Grassroots Programs'],
    experience: ['Director at Youth Sports India (5 years)', 'Coach at National Sports Academy (6 years)'],
    education: ['Masters in Sports Management - Ahmedabad University', 'Bachelor in Physical Education - Vadodara University'],
    lookingFor: ['Sports Equipment Sponsorship', 'Training Partnerships'],
    offering: ['Coaching Expertise', 'Youth Networks', 'Sports Programs'],
    linkedin: 'linkedin.com/in/vikashpatel',
    cohort: '2021',
  },
  {
    email: 'anjum.khan@example.com',
    name: 'Anjum Khan',
    initials: 'AK',
    title: 'Interfaith Dialogue Facilitator',
    bio: 'Building bridges between communities through interfaith dialogue and cultural exchange programs.',
    location: 'Lucknow, India',
    skills: ['Interfaith Dialogue', 'Community Building', 'Peace Building'],
    expertise: ['Conflict Resolution', 'Community Engagement', 'Cultural Mediation'],
    experience: ['Director at Peace Builders India (5 years)', 'Community Organizer at NGOs (7 years)'],
    education: ['Masters in Theology - Lucknow University', 'Bachelor in Sociology - Delhi University'],
    lookingFor: ['Grant Funding', 'International Partnerships'],
    offering: ['Community Networks', 'Dialogue Facilitation', 'Training Programs'],
    linkedin: 'linkedin.com/in/anjumkhan',
    cohort: '2020',
  },
  {
    email: 'ravi.kumar.nair@example.com',
    name: 'Ravi Kumar Nair',
    initials: 'RN',
    title: 'Circular Economy Expert',
    bio: 'Designing circular economy solutions and waste management systems for businesses and cities.',
    location: 'Chennai, India',
    skills: ['Circular Economy', 'Waste Management', 'Sustainability'],
    expertise: ['Resource Efficiency', 'Supply Chain Optimization', 'Green Business'],
    experience: ['Consultant at Circular Solutions (6 years)', 'Environmental Manager at Fortune 500 (5 years)'],
    education: ['Masters in Environmental Management - Anna University', 'Bachelor in Chemical Engineering - IIT Madras'],
    lookingFor: ['Corporate Clients', 'Government Projects', 'Technology Partners'],
    offering: ['Circular Economy Expertise', 'Implementation Support', 'Business Case Development'],
    linkedin: 'linkedin.com/in/ravikumarnair',
    cohort: '2021',
  },
  {
    email: 'tara.mishra@example.com',
    name: 'Tara Mishra',
    initials: 'TM',
    title: 'Child Rights Advocate',
    bio: 'Fighting child labor and promoting education and protection for vulnerable children.',
    location: 'Indore, India',
    skills: ['Child Rights', 'Education', 'Child Protection'],
    expertise: ['Child Welfare', 'Education Policy', 'Rehabilitation Programs'],
    experience: ['Executive Director at Child Protect Foundation (6 years)', 'Field Officer at UNICEF (5 years)'],
    education: ['Masters in Social Work - Delhi University', 'Bachelor in Education - Indore University'],
    lookingFor: ['Partnership with Schools', 'Government Support', 'International Funding'],
    offering: ['Child Rights Expertise', 'Community Networks', 'Rehabilitation Programs'],
    linkedin: 'linkedin.com/in/taramishra',
    cohort: '2020',
  },
  {
    email: 'harsh.gupta@example.com',
    name: 'Harsh Gupta',
    initials: 'HG',
    title: 'Startup Mentor & Investor',
    bio: 'Mentoring early-stage startups and investing in social impact ventures. Backed 20+ startups.',
    location: 'Delhi, India',
    skills: ['Startup Mentoring', 'Investment', 'Business Strategy'],
    expertise: ['Venture Capital', 'Startup Scaling', 'Business Models'],
    experience: ['Founder of Catalyst Ventures Fund (4 years)', 'VP at TechStars (5 years)'],
    education: ['MBA from IIM Delhi', 'Bachelor in Engineering - Delhi University'],
    lookingFor: ['High-impact Startups', 'Co-investors'],
    offering: ['Investment Capital', 'Mentorship', 'Network Access'],
    twitter: '@harshgupta_inv',
    linkedin: 'linkedin.com/in/harshgupta',
    cohort: '2019',
  },
  {
    email: 'malini.chakraborty@example.com',
    name: 'Malini Chakraborty',
    initials: 'MC',
    title: 'Gender-Based Violence Prevention Specialist',
    bio: 'Creating safe spaces and supporting survivors of gender-based violence through counseling and advocacy.',
    location: 'Kolkata, India',
    skills: ['GBV Prevention', 'Counseling', 'Advocacy', 'Community Support'],
    expertise: ['Trauma Counseling', 'Legal Rights', 'Rehabilitation'],
    experience: ['Founder at Safe Spaces Initiative (5 years)', 'Counselor at Legal Aid Centers (6 years)'],
    education: ['Masters in Clinical Psychology - Kolkata University', 'Diploma in Law - Legal Education Institute'],
    lookingFor: ['Funding for Shelters', 'Legal Support Networks', 'Corporate CSR Partnerships'],
    offering: ['Counseling Services', 'Training Programs', 'Advocacy Support'],
    linkedin: 'linkedin.com/in/malinichakraborty',
    cohort: '2021',
  },
  {
    email: 'ashok.reddy@example.com',
    name: 'Ashok Reddy',
    initials: 'AR',
    title: 'Agricultural Tech Innovator',
    bio: 'Developing low-cost agricultural technologies for small and marginal farmers. Tech for farming.',
    location: 'Hyderabad, India',
    skills: ['AgriTech', 'IoT', 'Software Development', 'Farming'],
    expertise: ['Precision Agriculture', 'Farm Management Software', 'IoT Solutions'],
    experience: ['Founder at FarmTech Solutions (5 years)', 'Software Engineer at IBM (6 years)'],
    education: ['Masters in Computer Science - IIIT Hyderabad', 'Bachelor in Engineering - Andhra University'],
    lookingFor: ['Farmer Networks', 'Government Support', 'Venture Funding'],
    offering: ['Technology Solutions', 'Farmer Training', 'Implementation Support'],
    github: 'github.com/ashokreddy',
    linkedin: 'linkedin.com/in/ashokreddy',
    cohort: '2022',
  },
  {
    email: 'deepika.sharma@example.com',
    name: 'Deepika Sharma',
    initials: 'DS',
    title: 'Nutritionist & Public Health Expert',
    bio: 'Addressing malnutrition and promoting healthy lifestyles in rural communities.',
    location: 'Lucknow, India',
    skills: ['Nutrition', 'Public Health', 'Health Education'],
    expertise: ['Community Nutrition', 'Health Programs', 'Food Security'],
    experience: ['Program Director at NutriCare India (5 years)', 'Health Officer at WHO (4 years)'],
    education: ['Masters in Public Health Nutrition - Delhi University', 'Bachelor in Food Science - Lucknow University'],
    lookingFor: ['Health Program Partnerships', 'Government Collaborations'],
    offering: ['Nutrition Expertise', 'Health Education Materials', 'Program Design'],
    linkedin: 'linkedin.com/in/deepikasharma',
    cohort: '2021',
  },
  {
    email: 'sanjiv.kumar@example.com',
    name: 'Sanjiv Kumar',
    initials: 'SK',
    title: 'Vocational Training Pioneer',
    bio: 'Setting up skill development centers and providing vocational training to unemployed youth.',
    location: 'Patna, India',
    skills: ['Vocational Training', 'Skill Development', 'Employment'],
    expertise: ['Curriculum Development', 'Trainer Training', 'Placement Support'],
    experience: ['Director at Skills First India (6 years)', 'Training Manager at NGOs (5 years)'],
    education: ['Masters in Education - Patna University', 'Diploma in Vocational Training - National Institute'],
    lookingFor: ['Training Content Partnerships', 'Employer Linkages'],
    offering: ['Training Programs', 'Curriculum Content', 'Trainer Networks'],
    linkedin: 'linkedin.com/in/sanjivkumar',
    cohort: '2020',
  },
  {
    email: 'kavya.reddy@example.com',
    name: 'Kavya Reddy',
    initials: 'KR',
    title: 'STEM Education Promoter',
    bio: 'Building STEM programs for girls in rural India. Working with 50+ schools.',
    location: 'Bangalore, India',
    skills: ['STEM Education', 'Girls Empowerment', 'Curriculum Design'],
    expertise: ['STEM Pedagogy', 'Teacher Training', 'Resource Development'],
    experience: ['Founder at STEM for Girls (4 years)', 'Educator at Schools (6 years)'],
    education: ['Masters in Education Technology - Bangalore University', 'Bachelor in Physics - Delhi University'],
    lookingFor: ['Educational Partnerships', 'Funding', 'Corporate Sponsorships'],
    offering: ['STEM Curriculum', 'Teacher Training', 'Resource Materials'],
    linkedin: 'linkedin.com/in/kavyareddy',
    cohort: '2022',
  },
  {
    email: 'manish.singh@example.com',
    name: 'Manish Singh',
    initials: 'MS',
    title: 'Microfinance Specialist',
    bio: 'Providing microfinance and financial literacy to low-income entrepreneurs and women groups.',
    location: 'Varanasi, India',
    skills: ['Microfinance', 'Financial Literacy', 'Credit Management'],
    expertise: ['Micro-lending', 'Group Lending Models', 'Financial Inclusion'],
    experience: ['Director at Microfinance Solutions (6 years)', 'Credit Officer at Banks (5 years)'],
    education: ['Masters in Finance - Varanasi University', 'Bachelor in Commerce - Delhi University'],
    lookingFor: ['Investor Networks', 'Government Support', 'Lending Partnerships'],
    offering: ['Microfinance Expertise', 'Lending Framework', 'Financial Literacy Programs'],
    linkedin: 'linkedin.com/in/manishsingh',
    cohort: '2020',
  },
  {
    email: 'swati.patel@example.com',
    name: 'Swati Patel',
    initials: 'SP',
    title: 'Digital Literacy Educator',
    bio: 'Teaching digital skills to seniors and underprivileged populations. Bridging digital divide.',
    location: 'Ahmedabad, India',
    skills: ['Digital Literacy', 'Technology Education', 'Community Engagement'],
    expertise: ['Online Safety', 'Basic Computing', 'Smartphone Skills'],
    experience: ['Founder at Digital Bridge India (4 years)', 'Tech Educator at NGOs (5 years)'],
    education: ['Masters in Information Technology - Ahmedabad University', 'Bachelor in Commerce - Gujarat University'],
    lookingFor: ['Technology Partnerships', 'Training Material Sponsorship'],
    offering: ['Digital Training Programs', 'Educational Content', 'Trainer Network'],
    linkedin: 'linkedin.com/in/swatipatel',
    cohort: '2021',
  },
  {
    email: 'raj.kumar@example.com',
    name: 'Raj Kumar',
    initials: 'RK',
    title: 'Supply Chain Optimization Expert',
    bio: 'Optimizing supply chains for social enterprises and fair trade organizations.',
    location: 'Gurgaon, India',
    skills: ['Supply Chain', 'Logistics', 'Operations', 'Business Strategy'],
    expertise: ['Fair Trade', 'Ethical Supply Chains', 'Efficiency'],
    experience: ['Consultant at Supply Chain Experts (6 years)', 'Operations Manager at Logistics Co (5 years)'],
    education: ['MBA from Delhi Business School', 'Bachelor in Engineering - Delhi University'],
    lookingFor: ['Consulting Opportunities', 'Enterprise Clients'],
    offering: ['Supply Chain Expertise', 'Process Optimization', 'Implementation Support'],
    linkedin: 'linkedin.com/in/rajkumar',
    cohort: '2021',
  },
  {
    email: 'nisha.prabhu@example.com',
    name: 'Nisha Prabhu',
    initials: 'NP',
    title: 'Conservation Biology Researcher',
    bio: 'Researching biodiversity conservation and ecosystem restoration in Western Ghats.',
    location: 'Goa, India',
    skills: ['Conservation Biology', 'Ecosystem Science', 'Research'],
    expertise: ['Wildlife Research', 'Habitat Restoration', 'Community Conservation'],
    experience: ['Research Fellow at Wildlife Institute (6 years)', 'Field Scientist at Conservation NGO (4 years)'],
    education: ['PhD in Conservation Biology - University of Goa', 'Masters in Biology - Delhi University'],
    lookingFor: ['Research Funding', 'International Collaborations', 'Publication Support'],
    offering: ['Research Expertise', 'Field Data', 'Conservation Networks'],
    linkedin: 'linkedin.com/in/nishaprabhu',
    cohort: '2021',
  },
  {
    email: 'suresh.agarwal@example.com',
    name: 'Suresh Agarwal',
    initials: 'SA',
    title: 'Cooperative Development Specialist',
    bio: 'Strengthening farmer cooperatives and self-help groups for collective action.',
    location: 'Jaipur, India',
    skills: ['Cooperative Development', 'Group Formation', 'Community Economics'],
    expertise: ['Cooperative Management', 'Value Addition', 'Market Linkages'],
    experience: ['Director at Cooperative Development Foundation (7 years)', 'Extension Officer at Agricultural Department (5 years)'],
    education: ['Masters in Cooperative Management - Jaipur University', 'Bachelor in Agriculture - Rajasthan University'],
    lookingFor: ['Government Partnerships', 'Funding', 'Technology Integration'],
    offering: ['Cooperative Expertise', 'Group Formation Support', 'Training Programs'],
    linkedin: 'linkedin.com/in/sureshagarwal',
    cohort: '2019',
  },
  {
    email: 'isha.kapoor@example.com',
    name: 'Isha Kapoor',
    initials: 'IK',
    title: 'Social Media & Digital Marketing Strategist',
    bio: 'Helping nonprofits and social enterprises build digital presence and online communities.',
    location: 'Mumbai, India',
    skills: ['Digital Marketing', 'Social Media', 'Content Strategy', 'Community Building'],
    expertise: ['Social Campaign Strategy', 'Influencer Networks', 'Digital Fundraising'],
    experience: ['Founder at SocialForGood Media (3 years)', 'Digital Strategist at Ad Agencies (5 years)'],
    education: ['Masters in Digital Marketing - Mumbai University', 'Bachelor in Communication - Delhi University'],
    lookingFor: ['NGO Partnerships', 'Project Collaborations'],
    offering: ['Digital Strategy', 'Content Creation Support', 'Media Networks'],
    twitter: '@ishakapoor_dm',
    linkedin: 'linkedin.com/in/ishakapoor',
    cohort: '2022',
  },
  {
    email: 'vikram.sharma@example.com',
    name: 'Vikram Sharma',
    initials: 'VS',
    title: 'Data Analytics for Good Specialist',
    bio: 'Using data analytics to measure impact and drive decision-making in social sector.',
    location: 'Bangalore, India',
    skills: ['Data Analytics', 'Impact Measurement', 'Data Science'],
    expertise: ['Impact Metrics', 'Dashboard Development', 'Data Visualization'],
    experience: ['Data Scientist at Analytics Firm (5 years)', 'Research Analyst at Think Tank (4 years)'],
    education: ['Masters in Data Science - Bangalore University', 'Bachelor in Statistics - Delhi University'],
    lookingFor: ['Impact Measurement Projects', 'Research Collaborations'],
    offering: ['Data Analytics Expertise', 'Impact Framework', 'Dashboard Development'],
    github: 'github.com/vikramsharma',
    linkedin: 'linkedin.com/in/vikramsharma',
    cohort: '2021',
  },
  {
    email: 'priyanka.singh@example.com',
    name: 'Priyanka Singh',
    initials: 'PS',
    title: 'Climate Action Advocate',
    bio: 'Promoting climate resilience and green practices in agricultural communities.',
    location: 'Patna, India',
    skills: ['Climate Action', 'Environmental Sustainability', 'Community Engagement'],
    expertise: ['Climate Resilience', 'Green Agriculture', 'Renewable Energy'],
    experience: ['Director at Climate Action India (4 years)', 'Program Officer at Climate NGO (5 years)'],
    education: ['Masters in Climate Science - Delhi University', 'Bachelor in Environmental Studies - Patna University'],
    lookingFor: ['Climate Projects', 'International Partnerships', 'Funding'],
    offering: ['Climate Expertise', 'Community Mobilization', 'Training Programs'],
    linkedin: 'linkedin.com/in/priyankasingh',
    cohort: '2021',
  },
  {
    email: 'arun.nair@example.com',
    name: 'Arun Nair',
    initials: 'AN',
    title: 'Legal Aid & Rights Advocate',
    bio: 'Providing free legal services and rights education to marginalized communities.',
    location: 'Thiruvananthapuram, India',
    skills: ['Legal Aid', 'Rights Education', 'Advocacy'],
    expertise: ['Constitutional Law', 'Labor Rights', 'Consumer Rights'],
    experience: ['Director at Legal Rights Foundation (5 years)', 'Lawyer at Legal Aid Centers (6 years)'],
    education: ['Masters in Constitutional Law - Law University', 'Bachelor of Laws - Delhi University'],
    lookingFor: ['Legal Support Networks', 'Government Partnerships'],
    offering: ['Legal Expertise', 'Rights Training', 'Advocacy Support'],
    linkedin: 'linkedin.com/in/arunair',
    cohort: '2020',
  },
];

function escapeString(str) {
  return str.replace(/'/g, "''");
}

memberDataList.forEach((member, index) => {
  const profileId = `profile-${String(index + 1).padStart(3, '0')}`;
  const userId = `user-${String(index + 1).padStart(3, '0')}`;
  const title = escapeString(member.title);
  const bio = escapeString(member.bio);
  const skills = JSON.stringify(member.skills);
  const expertise = JSON.stringify(member.expertise);
  const experience = JSON.stringify(member.experience);
  const education = JSON.stringify(member.education);
  const lookingFor = JSON.stringify(member.lookingFor);
  const offering = JSON.stringify(member.offering);
  const website = member.website ? `'${escapeString(member.website)}'` : 'NULL';
  const linkedin = member.linkedin ? `'${escapeString(member.linkedin)}'` : 'NULL';
  const twitter = member.twitter ? `'${escapeString(member.twitter)}'` : 'NULL';
  const github = member.github ? `'${escapeString(member.github)}'` : 'NULL';
  const joinedDate = "'2024-01-15'";
  const cohort = `'${member.cohort}'`;

  const sql = `INSERT INTO "Profile" (id, "userId", title, bio, skills, expertise, experience, education, "lookingFor", offering, website, linkedin, twitter, github, "joinedDate", cohort) VALUES ('${profileId}', '${userId}', '${title}', '${bio}', '${skills}', '${expertise}', '${experience}', '${education}', '${lookingFor}', '${offering}', ${website}, ${linkedin}, ${twitter}, ${github}, ${joinedDate}, ${cohort}) ON CONFLICT ("userId") DO NOTHING;`;

  console.log(sql);
});